# Generated by Django 3.2.9 on 2022-06-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_auto_20220617_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='public_cases',
            field=models.JSONField(default=list),
        ),
    ]
